const TYPES = {
  LOADING_DATA: "LOADING DATA",
  FETCH_DATA: "FETCH DATA",
  LOADED_DATA_SUCCESS: "LOADED_DATA_SUCCESS",
  LOADED_DATA_ERROR: "LOADED_DATA_ERROR",
  POST_REGIST: "POST_REGIST",
  POST_LOGIN: "POST_LOGIN",
}

export default TYPES
