const TYPES = {
  LOADING_DATA: "LOADING DATA",
  FETCH_DATA: "FETCH DATA",
  LOADED_DATA_SUCCESS: "LOADED_DATA_SUCCESS",
  LOADED_DATA_ERROR: "LOADED_DATA_ERROR",
  REGIST_SUCCESS: "REGIST_SUCCESS",
}

export default TYPES
